version: "3"
services:
  database:
    image: postgres:12
    container_name: pipeline-database
    env_file:
      - auth.env
    networks:
      - pgnetwork
    ports:
      - 5431:5432
    volumes:
      - ./database:/var/lib/postgresql/data

  pipeline:
    build:
      context: .
      args:
        - BUILDKIT_PROGRESS=plain
        - BUILDKIT_PROVENANCE=false
        - BUILDKIT_SBOM=false
    env_file:
      - auth.env
    networks:
      - pgnetwork
    ports:
      - 8000:8000
      
  shiny:
    build: frontend
    networks:
      - pgnetwork
    ports:
      - 3838:3838
    volumes:
      - /data01/shinyapps:/srv/shiny-server
      - /data01/shinylogs:/var/log/shiny-server
      
  

volumes:
  database:
  shinyapps:
  shinylogs:

networks:
  pgnetwork:
